export default [
  {
    category: 'education',
    title: 'Graduated from University of the Arts',
    desc: "Although I didn't really want to finish school, I thought it would be best to finish it to please my parents?",
    date: ISODate('2011-09-01'),
    start: true,
  },
  {
    category: 'profession',
    title: 'Started a business',
    desc: 'Rather than going through the traditional route and trying to find work. I decided to start a business instead. YouTube was relatively new at the time and my business partner and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'profession',
    title: 'Reload Sessions Ltd is created',
    desc: 'Under the name Reload Sessions, we created a video production company championing unsigned musicians in the London music scene',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'profession',
    title: '2,000,000 views and counting',
    desc: 'With the YouTube channel views and subscribers steadily rising, new opportunities kept on opening up for the business.',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'profession',
    title: 'Taking it to America',
    desc: 'After securing enough funding, we were able to take the concept of Reload Sessions to the USA.',
    date: ISODate('2016-08-01'),
    link: 'https://www.youtube.com/watch?v=6tI8edYShYY',
    image: '',
  },
  {
    category: 'All good things come to an end',
    title: 'Started a business',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'Entering a new market',
    title: 'Started a business',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'A change of scenary',
    title: 'Started a business',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'Covid hits the world',
    title: 'Started a business',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'Catching the bug',
    title: 'Started a business',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: 'A complete career change',
    title: 'Started a business',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
  {
    category: '',
    title: 'Starting the startup life',
    desc: 'Rather than trying to find work after graduation I decided to start a business. YouTube was relatively new at the time and I saw an opportunity',
    date: ISODate('2012-01-01'),
    image: '',
  },
]
