export default [
  {
    title: 'Graduated from University of the Arts London',
    desc: 'After 4 years of studying I walked away with a Bachelor of Arts in Graphic & Media Design.',
    category: 'education',
    date: ISODate('2011-09-01'),
    image:
      'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2F2017.splicefestival.com%2Fwp-content%2Fuploads%2F2016%2F04%2Fweb_ual-entrance-900x600.jpg&f=1&nofb=1',
    start: true,
  },
  {
    title: 'Started a business',
    desc: 'Rather than going down the traditional route and trying to find work, I decided to start a business instead. YouTube was relatively new at the time and my business partner and I saw an opportunity. Under the name Reload Sessions Ltd, we created a video production company championing unsigned musicians in the London music scene',
    category: 'career',
    date: ISODate('2012-01-01'),
    buttonText: 'View the channel',
    buttonLink: 'https://www.youtube.com/user/ReloadSessions',
  },
  {
    title: '2,000,000 views and counting',
    desc: 'With the YouTube channel views and subscribers steadily rising, new opportunities kept on opening up for the business.',
    category: 'career',
    date: ISODate('2012-07-01'),
    image: '/timeline-reload.jpg',
  },
  {
    title: 'Taking the company to America',
    desc: 'After securing enough funding, we were able to take the concept of Reload Sessions to the USA.',
    category: 'career',
    date: ISODate('2016-05-01'),
    buttonText: 'View the video',
    buttonLink: 'https://www.youtube.com/watch?v=6tI8edYShYY',
  },
  {
    title: 'Closing down the business',
    desc: "After 6 years, 16,000,000+ total views, 85,000+ subscribers, and 700+ videos it was time to shut down the business. Unfortunately, we couldn't keep the business going, but I had learned a tremendous amount from the experience and grateful that I made the decision to start a company in the first place.",
    category: 'career',
    date: ISODate('2018-06-01'),
  },
  {
    title: 'Entering a new market',
    desc: 'Straight after shutting down the company a new opportunity presented itself to be the Creative Director for a relatively new company in the vegan industry. It was something totally new and I was excited for a new challenge.',
    category: 'career',
    date: ISODate('2018-10-01'),
  },
  {
    title: 'A change of scenary',
    desc: 'Having had a long distance relationship for several years, I decided to relocate to Sweden to live closer to my partner.',
    category: 'location',
    date: ISODate('2019-01-01'),
  },
  {
    title: 'Covid hits the world',
    desc: 'Several businesses got hit hard, sadly ours was no different. After much consideration, I decided that it was time for me to move on from my work and figure out my next chapter in life.',
    category: 'career',
    date: ISODate('2020-10-01'),
  },
  {
    title: 'Increasing my skills',
    desc: 'I had always wanted to understand programming, and now that I had more free time on my hands I thought it was about time to start learning.',
    category: 'education',
    date: ISODate('2020-10-02'),
  },
  {
    title: 'A new career path',
    desc: 'I managed to land a new role in a new field - UX/UI Designer for a Digital Agency in Sweden. It was something completely different to what I had done in the past, but I had always wanted to work in the field of tech. Again, I embraced a new challenge.',
    category: 'career',
    date: ISODate('2021-04-01'),
  },
  {
    title: 'Making senior in 6 months',
    desc: 'After going all-in and showing both competence and potential, I was able to land the role of Competence Lead UX/UI designer with SQLI Nordics AB',
    category: 'career',
    date: ISODate('2022-06-01'),
    buttonText: 'View SQLI Nordics',
    buttonLink: 'https://www.sqli.com/se-sv',
  },
  {
    title: 'Joining a new small team',
    desc: "A new and exciting opportunity presented itself and I was able to land the UX Lead Designer role with Orbi. Being the 8th hire in the relatively new company, I'm excited to both grow in my role as well as the company itself.",
    category: 'career',
    date: ISODate('2022-06-01'),
    buttonText: 'View Orbi',
    buttonLink: 'https://www.orbiapp.io/',
  },
]
